apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
spec:
  selector:
    app: selenium-hub
  ports:
    - name: grid-port
      protocol: TCP
      port: 4444
      targetPort: 4444
    - name: event-bus-publish
      protocol: TCP
      port: 4442
      targetPort: 4442
    - name: event-bus-subscribe
      protocol: TCP
      port: 4443
      targetPort: 4443
