apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-hub
  template:
    metadata:
      labels:
        app: selenium-hub
    spec:
      containers:
      - name: selenium-hub
        image: selenium/hub:latest
        ports:
        - containerPort: 4444  
        - containerPort: 4442 
        - containerPort: 4443  
        env:
        - name: SE_OPENTELEMETRY_ENABLED
          value: "false"
